官方源代码/MockSchool-master/章节代码/章节41/MockSchoolManagement/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MockSchoolManagement.Models
{
    /// <summary>
    /// 系部
    /// </summary>
    public class Department
    {
        public int DepartmentID { get; set; }
        [Display(Name = "院系名称")]
        [StringLength(50, MinimumLength = 3)]
        public string Name { get; set; }

        /// <summary>
        /// 预算
        /// </summary>
        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        [Display(Name = "预算")]

        public decimal Budget { get; set; }

        /// <summary>
        /// 成立时间
        /// </summary>
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "成立时间")]
        public DateTime StartDate { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }

        [Display(Name = "负责人")]

        public int? TeacherID { get; set; }
        /// <summary>
        /// 系部主任
        /// </summary
        public virtual Teacher Administrator { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}

官方源代码/MockSchool-master/章节代码/章节41/MockSchoolManagement/ViewModels/Departments/DepartmentCreateViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MockSchoolManagement.Models;
using System;
using System.ComponentModel.DataAnnotations;

namespace MockSchoolManagement.ViewModels.Departments
{
    public class DepartmentCreateViewModel
    {
        public int DepartmentID { get; set; }

        [StringLength(50, MinimumLength = 3)]
        [Display(Name = "院系名称")]
        public string Name { get; set; }

        /// <summary>
        /// 预算
        /// </summary>
        [DataType(DataType.Currency)]
        [Display(Name = "预算")]
        public decimal Budget { get; set; }

        /// <summary>
        /// 成立时间
        /// </summary>
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "成立时间")]
        public DateTime StartDate { get; set; }

        [Timestamp]
        public byte[] RowVersion { get; set; }

        [Display(Name = "负责人")]
        public SelectList TeacherList { get; set; }

        public int? TeacherID { get; set; }

        /// <summary>
        /// 系部主任
        /// </summary
        public Teacher Administrator { get; set; }
    }
}

官方源代码/MockSchool-master/章节代码/章节41/MockSchoolManagement/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MockSchoolManagement.Application.Teachers;
using MockSchoolManagement.Infrastructure;
using MockSchoolManagement.Infrastructure.Repositories;
using MockSchoolManagement.Models;
using MockSchoolManagement.ViewModels.Departments;
using System.Linq;
using System.Threading.Tasks;

namespace MockSchoolManagement.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly IRepository<Department, int> _departmentRepository;
        private readonly IRepository<Teacher, int> _teacherRepository;
        private readonly IDepartmentsService _departmentsService;
        private readonly AppDbContext _dbcontext;

        public DepartmentsController(
            IRepository<Department, int> departmentRepository,
            IDepartmentsService departmentsService,
            IRepository<Teacher, int> teacherRepository, AppDbContext dbcontext)
        {
            _departmentRepository = departmentRepository;
            _departmentsService = departmentsService;
            _teacherRepository = teacherRepository;
            _dbcontext = dbcontext;
        }

        public async Task<IActionResult> Index(GetDepartmentInput input)
        {
            var models = await _departmentsService.GetPagedDepartmentsList(input);
            return View(models);
        }

        #region 编辑

        public async Task<IActionResult> Edit(int id)
        {

          
            //    var department = _dbcontext.Departments
            //        .Single(b => b.DepartmentID == id);
            ////Collection()方法表示，实体与另外一个Collection集合之间的关联关系
            //_dbcontext.Entry(department)
            //        .Collection(b => b.Courses)
            //        .Load();

            ////  Reference()方法表示，可用于两个实体时间的关联
            //_dbcontext.Entry(department)
            //        .Reference(b => b.Administrator)
            //        .Load();


           var department = await _departmentRepository.FirstOrDefaultAsync(a => a.DepartmentID ==id); 

            var model = await _departmentRepository.GetAll().Include(a => a.Administrator).AsNoTracking()
            .FirstOrDefaultAsync(a => a.DepartmentID == id);

            if (model == null)
            {
                ViewBag.ErrorMessage = $"教师{id}的信息不存在，请重试。";
                return View("NotFound");
            }
            var teacherList = TeachersDropDownList();
            var dto = new DepartmentCreateViewModel
            {
                DepartmentID = model.DepartmentID,
                Name = model.Name,
                Budget = model.Budget,
                StartDate = model.StartDate,
                TeacherID = model.TeacherID,
                Administrator = model.Administrator,
                RowVersion = model.RowVersion,
                TeacherList = teacherList
            };
            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DepartmentCreateViewModel input)
        {
            if (ModelState.IsValid)
            {
               


                var model = await _departmentRepository.GetAll().Include(a => a.Administrator).FirstOrDefaultAsync(a => a.DepartmentID == input.DepartmentID);

                if (model == null)
                {
                    ViewBag.ErrorMessage = $"教师{input.DepartmentID}的信息不存在，请重试。";
                    return View("NotFound");
                }
                model.DepartmentID = input.DepartmentID;
                model.Name = input.Name;
                model.Budget = input.Budget;
                model.StartDate = input.StartDate;
                model.TeacherID = input.TeacherID;

                //从数据库中获取Department实体中的 RowVersion属性，然后将input.RowVersion赋值到OriginalValue中，EF Core会将两个值进行比较。
                _dbcontext.Entry(model).Property("RowVersion").OriginalValue = input.RowVersion;

                try
                {   //UpdateAsync方法执行SaveChangesAsync()方法时，如果检测到并发冲突则会触发DbUpdateConcurrencyException异常
                    await _departmentRepository.UpdateAsync(model);
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException ex)
                {   //异常触发后，获取异常的实体
                    var exceptionEntry = ex.Entries.Single();
                    var clientValues = (Department)exceptionEntry.Entity;
                    //从数据库中获取该异常实体信息
                    var databaseEntry = exceptionEntry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {//如果异常实体为null，则表示该行已经被删除
                        ModelState.AddModelError(string.Empty, "无法进行数据的修改。该部门信息已经被其他人所删除！");
                    }
                    else
                    {     //将异常实体中错误信息信息，精确到具体字段程序到视图中。
                        var databaseValues = (Department)databaseEntry.ToObject();
                        if (databaseValues.Name != clientValues.Name)
                            ModelState.AddModelError("Name", $"当前值:{databaseValues.Name}");
                        if (databaseValues.Budget != clientValues.Budget)
                            ModelState.AddModelError("Budget", $"当前值:{databaseValues.Budget}");
                        if (databaseValues.StartDate != clientValues.StartDate)
                            ModelState.AddModelError("StartDate", $"当前值:{databaseValues.StartDate}");
                        if (databaseValues.TeacherID != clientValues.TeacherID)
                        {
                            var teacherEntity =
                                 await _teacherRepository.FirstOrDefaultAsync(a => a.Id == databaseValues.TeacherID);
                            ModelState.AddModelError("TeacherId", $"当前值:{teacherEntity?.Name}");
                        }
                        ModelState.AddModelError("", "你正在编辑的记录已经被其他用户所修改，编辑操作已经被取消，数据库当前的值已经显示在页面上。请再次点击保存。否则请返回列表。");
                        input.RowVersion = databaseValues.RowVersion;
                        //记得初始化老师列表
                        input.TeacherList = TeachersDropDownList();
                        ModelState.Remove("RowVersion");
                    }
                }
            }
            return View(input);
        }

        #endregion 编辑

        #region 添加

        public IActionResult Create()
        {
            var dto = new DepartmentCreateViewModel
            {
                TeacherList = TeachersDropDownList()
            };
            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Create(DepartmentCreateViewModel input)
        {
            if (ModelState.IsValid)
            {
                Department model = new Department
                {
                    StartDate = input.StartDate,
                    DepartmentID = input.DepartmentID,
                    TeacherID = input.TeacherID,
                    Budget = input.Budget,
                    Name = input.Name,
                };
                await _departmentRepository.InsertAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        #endregion 添加

        #region 删除

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var model = await _departmentRepository.FirstOrDefaultAsync(a => a.DepartmentID == id);

            if (model == null)
            {
                ViewBag.ErrorMessage = $"院系编号{id}的信息不存在，请重试。";
                return View("NotFound");
            }

            await _departmentRepository.DeleteAsync(a => a.DepartmentID == id);
            return RedirectToAction(nameof(Index));
        }

        #endregion 删除

        #region 详情

        public async Task<IActionResult> Details(int Id)
        {
            string query = "SELECT * FROM dbo.Departments WHERE DepartmentID={0}";
            var model = await _dbcontext.Departments.FromSqlRaw(query, Id).Include(d => d.Administrator)
                      .AsNoTracking()
                      .FirstOrDefaultAsync();
            if (model == null)
            {
                ViewBag.ErrorMessage = $"部门ID{Id}的信息不存在，请重试。";
                return View("NotFound");
            }

            return View(model);
        }

        #endregion 详情

        /// <summary>
        /// 教师的下拉列表
        /// </summary>
        /// <param name="selectedTeacher"></param>
        private SelectList TeachersDropDownList(object selectedTeacher = null)
        {
            var models = _teacherRepository.GetAll().OrderBy(a => a.Name).AsNoTracking().ToList();
            var dtos = new SelectList(models, "Id", "Name", selectedTeacher);
            return dtos;
        }

        //[Route("")]//使 List()成为默认路由入口
        public string List()
        {
            return "我是Departments控制器的List()操作方法 ";
        }
    }
}

官方源代码/MockSchool-master/章节代码/章节41/MockSchoolManagement/Views/Departments/Create.cshtml
@using  MockSchoolManagement.ViewModels.Departments
@model DepartmentCreateViewModel
@{ ViewBag.Title = "创建院系"; }

<form asp-action="Create" method="post" class="mt-3">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="DepartmentID" />
    <div class="form-group row">
        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Name" class="form-control" placeholder="请输入院系名称" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="StartDate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="StartDate" type="date" class="form-control" placeholder="请输入成立时间" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Budget" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Budget" class="form-control" placeholder="请输入预算" />
            <span asp-validation-for="Budget" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="TeacherList" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="TeacherID"
                    class="custom-select mr-sm-2"
                    asp-items="@Model.TeacherList">
                <option value="">请选择</option>
            </select>
            <span asp-validation-for="TeacherList" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">创建</button>
        </div>
    </div>
</form>

官方源代码/MockSchool-master/章节代码/章节41/MockSchoolManagement/Views/Departments/Details.cshtml
@model Department
@{
    ViewBag.Title = "部门详情信息";
}
<div class="row justify-content-center m-3">
    <div class="col-sm-6">

        <div class="card bg-light mb-3" style="max-width: 18rem;">
            <div class="card-header">
                <h1>@Model.Name  详情 </h1>
            </div>
            <div class="card-body text-center">
                <h5 class="card-title">
                    @Html.DisplayNameFor(a => a.Name) : @Model.Name
                </h5>
                <h5 class="card-title">@Html.DisplayNameFor(a => a.StartDate) : @Html.DisplayFor(a => a.StartDate)</h5>
                <h5 class="card-title">@Html.DisplayNameFor(a => a.Budget) : @Html.DisplayFor(a => a.Budget)</h5>
                <h5 class="card-title">@Html.DisplayNameFor(a => a.TeacherID): @Model.Administrator.Name</h5>
            </div>
            <div class="card-footer text-center">
                <a asp-action="Index" class="btn btn-info">返回</a>
                <a asp-action="edit" asp-route-Id="@Model.DepartmentID" class="btn btn-primary">编辑</a>
            </div>
        </div>
    </div>
</div>

官方源代码/MockSchool-master/章节代码/章节41/MockSchoolManagement/Views/Departments/Edit.cshtml
@using  MockSchoolManagement.ViewModels.Departments
@model DepartmentCreateViewModel
@{ ViewBag.Title = "编辑院系"; }

<form asp-action="Edit" method="post" class="mt-3">
    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="DepartmentID" />
    <input type="hidden" asp-for="RowVersion" />

    <div class="form-group row">
        <label asp-for="Name" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Name" class="form-control" placeholder="请输入院系名称" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="StartDate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="StartDate" type="date" class="form-control" placeholder="请成立时间" />
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Budget" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Budget" class="form-control" placeholder="请输入预算" />
            <span asp-validation-for="Budget" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="TeacherList" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="TeacherID" class="custom-select mr-sm-2" asp-items="@Model.TeacherList">
                <option value="">请选择</option>
            </select>
            <span asp-validation-for="TeacherID" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">更新</button>
            <a asp-action="index" class="btn btn-primary">取消</a>
        </div>
    </div>
</form>

官方源代码/MockSchool-master/章节代码/章节41/MockSchoolManagement/Views/Departments/Index.cshtml
@using MockSchoolManagement.Application.Dtos;
@model PagedResultDto<Department>

@{
    ViewBag.Title = "院系列表页面";
}
<h1>院系列表</h1>
<form asp-action="Index" method="get">

    <div class="form-actions no-color">
        <input type="hidden" name="CurrentPage" value="@Model.CurrentPage" />
        <input type="hidden" name="Sorting" value="@Model.Sorting" />
        <p>
            请输入名称: <input type="text" name="FilterText" value="@Model.FilterText" />
            <input type="submit" value="查询" class="btn btn-outline-dark" /> |
            <a asp-action="Index">返回所有列表</a>| <a asp-action="Create">
                添加
            </a>
        </p>
    </div>
</form>

<div class="  table-responsive-sm">
    @if (Model.Data.Any())
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>

                    <th scope="col" class="sort-link">
                        <a asp-action="Index"
                           asp-route-Sorting="Name" asp-route-CurrentPage="@Model.CurrentPage" asp-route-FilterText="@Model.FilterText">
                            院系名称
                        </a>
                    </th>
                    <th>
                        <a asp-action="Index" asp-route-Sorting="StartDate " asp-route-CurrentPage="@Model.CurrentPage" asp-route-FilterText="@Model.FilterText">
                            成立时间
                        </a>
                    </th>
                    <th>
                        <a asp-action="Index" asp-route-Sorting="Budget " asp-route-CurrentPage="@Model.CurrentPage" asp-route-FilterText="@Model.FilterText">
                            预算
                        </a>
                    </th>
                    <th>负责人</th>
                    <th scope="col">操作</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model.Data)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td> @Html.DisplayFor(modelItem => item.StartDate) </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Budget)
                        </td>
                        <td>@item.Administrator.Name</td>
                        <td>
                            <form method="post" asp-action="Delete" asp-route-id="@item.DepartmentID">
                                <a asp-controller="Departments" class="btn btn-info" asp-action="Details" asp-route-Id="@item.DepartmentID">查看</a>
                                <a asp-controller="Departments" asp-action="Edit" asp-route-Id="@item.DepartmentID" class="btn btn-primary m-1">编辑</a>
                                <span id="confirmDeleteSpan_@item.DepartmentID" style="display: none">
                                    <span>你确定你要删除?</span>
                                    <button type="submit" class="btn btn-danger">是</button>
                                    <a href="#" class="btn btn-primary" onclick="confirmDelete('@item.DepartmentID', false)">否</a>
                                </span>
                                <span id="deleteSpan_@item.DepartmentID">
                                    <a href="#" class="btn btn-danger" onclick="confirmDelete('@item.DepartmentID', true)">删除</a>
                                </span>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    @await Html.PartialAsync("_Pagination")
</div>

@section Scripts {
    <script src="~/js/CustomScript.js" asp-append-version="true"></script>
}